name: Hub
version: 0.1
author: TheTonyk
description: Minecraft Hub Plugin
main: com.thetonyk.Hub.Main
softdepend: [ProtocolLib]

commands:
    fly:
        permission: global.flycommand
    gamemode:
        permission: global.gamemode
        aliases: [gm]
    lag:
        permission: global.lag
        aliases: [tps]
    ping:
        permission: global.ping
        aliases: [ms]
    whitelist:
        permission: global.whitelist
        aliases: [wl, wh]
    clear:
        permission: global.clear
    text:
        permission: global.text
    health:
        permission: global.health
        aliases: [h, life]
    heal:
        permission: global.heal
    sethealth:
        permission: global.sethealth
    give:
        permission: global.give
    list:
        permission: global.list
    effect:
        permission: global.effect
        aliases: [effects]
    teleport:
        permission: global.teleport
        aliases: [tp]
